// Generated by gencpp from file newmode/mode_msg.msg
// DO NOT EDIT!


#ifndef NEWMODE_MESSAGE_MODE_MSG_H
#define NEWMODE_MESSAGE_MODE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace newmode
{
template <class ContainerAllocator>
struct mode_msg_
{
  typedef mode_msg_<ContainerAllocator> Type;

  mode_msg_()
    : mode(0)
    , cnt(0)
    , angle(0.0)  {
    }
  mode_msg_(const ContainerAllocator& _alloc)
    : mode(0)
    , cnt(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef int32_t _cnt_type;
  _cnt_type cnt;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::newmode::mode_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::newmode::mode_msg_<ContainerAllocator> const> ConstPtr;

}; // struct mode_msg_

typedef ::newmode::mode_msg_<std::allocator<void> > mode_msg;

typedef boost::shared_ptr< ::newmode::mode_msg > mode_msgPtr;
typedef boost::shared_ptr< ::newmode::mode_msg const> mode_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::newmode::mode_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::newmode::mode_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace newmode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'newmode': ['/home/ri/soonrobo/src/newmode/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::newmode::mode_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::newmode::mode_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmode::mode_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmode::mode_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmode::mode_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmode::mode_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::newmode::mode_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f38f182f4939ebaee1d345a52aa2a3ad";
  }

  static const char* value(const ::newmode::mode_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf38f182f4939ebaeULL;
  static const uint64_t static_value2 = 0xe1d345a52aa2a3adULL;
};

template<class ContainerAllocator>
struct DataType< ::newmode::mode_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "newmode/mode_msg";
  }

  static const char* value(const ::newmode::mode_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::newmode::mode_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n\
int32 cnt\n\
float32 angle\n\
";
  }

  static const char* value(const ::newmode::mode_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::newmode::mode_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.cnt);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mode_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::newmode::mode_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::newmode::mode_msg_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    s << indent << "cnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cnt);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEWMODE_MESSAGE_MODE_MSG_H
