// Generated by gencpp from file newmode/msg_lane.msg
// DO NOT EDIT!


#ifndef NEWMODE_MESSAGE_MSG_LANE_H
#define NEWMODE_MESSAGE_MSG_LANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace newmode
{
template <class ContainerAllocator>
struct msg_lane_
{
  typedef msg_lane_<ContainerAllocator> Type;

  msg_lane_()
    : angle(0.0)
    , sw(false)  {
    }
  msg_lane_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , sw(false)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef uint8_t _sw_type;
  _sw_type sw;





  typedef boost::shared_ptr< ::newmode::msg_lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::newmode::msg_lane_<ContainerAllocator> const> ConstPtr;

}; // struct msg_lane_

typedef ::newmode::msg_lane_<std::allocator<void> > msg_lane;

typedef boost::shared_ptr< ::newmode::msg_lane > msg_lanePtr;
typedef boost::shared_ptr< ::newmode::msg_lane const> msg_laneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::newmode::msg_lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::newmode::msg_lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace newmode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'newmode': ['/home/ri/soonrobo/src/newmode/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::newmode::msg_lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::newmode::msg_lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmode::msg_lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmode::msg_lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmode::msg_lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmode::msg_lane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::newmode::msg_lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e30d84a69dca6130a8987a887aa0a0fd";
  }

  static const char* value(const ::newmode::msg_lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe30d84a69dca6130ULL;
  static const uint64_t static_value2 = 0xa8987a887aa0a0fdULL;
};

template<class ContainerAllocator>
struct DataType< ::newmode::msg_lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "newmode/msg_lane";
  }

  static const char* value(const ::newmode::msg_lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::newmode::msg_lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n\
bool sw\n\
";
  }

  static const char* value(const ::newmode::msg_lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::newmode::msg_lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.sw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::newmode::msg_lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::newmode::msg_lane_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "sw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEWMODE_MESSAGE_MSG_LANE_H
